# Generated by Django 4.2.7 on 2023-11-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0005_alter_curriculumvitae_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%Y/%m'),
        ),
    ]
