# Generated by Django 4.2.7 on 2023-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='image',
            field=models.ImageField(upload_to='upload/%Y/%m'),
        ),
    ]
