# Generated by Django 4.2.7 on 2023-11-20 12:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('number_of_employees', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='upload/%Y/%m')),
                ('social_link', models.CharField(max_length=254, null=True)),
                ('industry', models.CharField(max_length=50)),
                ('followers', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
