# Generated by Django 4.2.7 on 2023-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/default-avatar.jpg', null=True, upload_to='upload/%Y/%m'),
        ),
    ]
