# Generated by Django 4.2.7 on 2023-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_name_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='upload/%Y/%m'),
        ),
    ]
