# Generated by Django 4.2.7 on 2023-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=150, null=True, unique=True),
        ),
    ]
