# Generated by Django 4.2.7 on 2023-11-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
