# Generated by Django 4.2.7 on 2023-11-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_first_name_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
