# Generated by Django 4.2.7 on 2023-11-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wage_start', models.IntegerField()),
                ('wage_end', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('position', models.CharField(max_length=50)),
                ('experience_year', models.CharField(max_length=20)),
                ('number_of_recruits', models.IntegerField(null=True)),
                ('work_form', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jds', to='company.company')),
            ],
        ),
    ]
