# Generated by Django 4.2.7 on 2023-11-16 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='users',
            field=models.ManyToManyField(related_name='jobs', through='job.JobApplications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobdescription'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
