# Generated by Django 4.2.7 on 2023-11-16 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_alter_jobdescription_benefits_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplications',
            new_name='JobApplication',
        ),
    ]
