# Generated by Django 4.2.7 on 2023-11-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobdescription_work_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('BOTH', 'Cả hai'), ('UNKNOWN', 'Không yêu cầu')], max_length=20, null=True),
        ),
    ]
