# Generated by Django 4.2.7 on 2023-11-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Male'), ('Nữ', 'Female'), ('Cả hai', 'Both'), ('Không yêu cầu', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='work_form',
            field=models.CharField(choices=[('Bán thời gian', 'Part Time'), ('Toàn thời gian', 'Full Time'), ('Cả hai', 'Both')], max_length=20),
        ),
    ]
