# Generated by Django 4.2.7 on 2023-11-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
