# Generated by Django 4.2.7 on 2023-11-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobdescription_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='work_form',
            field=models.CharField(choices=[('PART_TIME', 'Bán thời gian'), ('FULL_TIME', 'Toàn thời gian'), ('BOTH', 'Cả hai')], max_length=20),
        ),
    ]
